server:
  port: 12222
  error:
    include-binding-errors: always
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydb.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  cache:
    type: caffeine
  jackson:
    serialization:
      write-dates-as-timestamps: true
cache:
  caches:
    - name: httpRequestStatisticsCache
      expire-after-write: 10m
    - name: instanceHealthCache
      expire-after-write: 10m
    - name: instanceAbilityCache
      expire-after-write: 10m
    - name: instancePropertyCache
      expire-after-write: 1m
    - name: instanceActuatorCache
      expire-after-write: 1m
    - name: instanceHostnameCache
      expire-after-write: 10m
    - name: applicationHealthCache
      expire-after-write: 10m
    - name: applicationSystemPropertiesCache
      expire-after-write: 30m
    - name: applicationSystemEnvironmentCache
      expire-after-write: 30m